"""Generates results/jev-v1.template.md: every number in it is a named {{slot}} (§10).

    python -m jev_probe.template   # (re)write the committed template
"""

from __future__ import annotations

import sys

from jev_probe.analysis import CLASSES
from jev_probe.constants import CHANNEL_OF, CONDITIONS, METADATA_BORNE, TEMPLATE_PATH
from jev_probe.questions import CLASS_QUESTIONS, QUESTION_IDS, question_for_class

COND_NAME = {"P": "payload only (P)", "PM": "payload plus metadata (PM)"}


def s(name: str) -> str:
    return "{{" + name + "}}"


def rate(prefix: str) -> str:
    return f"{s(prefix + '.rate')} [{s(prefix + '.lo')}, {s(prefix + '.hi')}] ({s(prefix + '.k')}/{s(prefix + '.n')})"


def build() -> str:
    L: list[str] = []
    a = L.append
    a("# jev-v1 results: Jev as an advisory data-quality critic on GIGO-Bench")
    a("")
    a("> Generated by `python -m jev_probe.analysis` from the committed raw-response cache "
      "`responses/jev-v1.jsonl`. Every number below is a named slot filled by that command; none "
      "is entered by hand. Registration: `prereg/jev-v1.md` (tag `prereg-jev-v1`). Departures: "
      "`prereg/DEVIATIONS.md`.")
    a("")
    a("**Invariant.** Jev is measured here as an **advisory critic only**. Its answers were "
      "recorded and scored; they were never used to admit, block, repair or substitute evidence, "
      "and nothing below is a replacement for the deterministic predicates, which remain the "
      "enforcement mechanism and appear only as a baseline.")
    a("")
    a("## Run")
    a("")
    a("| field | value |")
    a("|---|---|")
    for k, label in (
        ("status", "status"), ("hypotheses_evaluated", "hypotheses evaluated"),
        ("items_complete", "items with all repeats in both conditions"),
        ("n_calls", "calls cached"), ("n_attempts", "HTTP attempts"), ("n_retries", "adapter retries"),
        ("n_segments", "run segments"), ("spend_usd", "spend, USD (usage-based)"),
        ("spend_committed_usd", "spend, USD (cap accounting, conservative)"),
        ("requested_model", "requested model"), ("model_versions", "returned model string(s)"),
        ("model_version_changed", "MODEL_VERSION_CHANGED"), ("endpoint", "endpoint"),
        ("sdk_version", "SDK version"), ("engine_pin", "engine pin (dqSarc)"),
        ("prereg_commit", "prereg commit"), ("prompt_sha256", "context sentence SHA-256"),
        ("questions_sha256", "question set SHA-256"), ("docs_sha256", "docs page SHA-256"),
    ):
        a(f"| {label} | {s('run.' + k)} |")
    a(f"| bootstrap | {s('analysis.bootstrap_b')} resamples, seed {s('analysis.bootstrap_seed')} |")
    a("")
    a("## Primary hypotheses (Holm over H1, H2, H3; two-sided, alpha 0.05)")
    a("")
    a("| hypothesis | estimate | 95% CI | p | Holm-adjusted p | verdict |")
    a("|---|---|---|---|---|---|")
    a(f"| H1: metadata-borne detection above chance (PM) | d = {s('H1.PM.pooled.d')} vs chance "
      f"{s('H1.PM.pooled.chance')}; difference {s('H1.PM.pooled.estimate')} | "
      f"[{s('H1.PM.pooled.ci_lo')}, {s('H1.PM.pooled.ci_hi')}] | {s('H1.PM.pooled.p')} | "
      f"{s('H1.PM.pooled.p_adj')} | {s('H1.PM.pooled.verdict')} |")
    a(f"| H2: calibration (PM, all 9 questions) | Spiegelhalter Z = {s('H2.PM.z')} "
      f"(bootstrap SE); BSS = {s('H2.PM.bss')} | BSS [{s('H2.PM.bss_lo')}, {s('H2.PM.bss_hi')}] | "
      f"{s('H2.PM.p')} | {s('H2.PM.p_adj')} | {s('H2.PM.verdict')} |")
    a(f"| H3: PM beats P on metadata-borne classes | PM {s('H3.meta.pm_rate')} vs P "
      f"{s('H3.meta.p_rate')}; difference {s('H3.meta.estimate')} (discordant b = "
      f"{s('H3.meta.b')}, c = {s('H3.meta.c')}, n = {s('H3.meta.n')}) | "
      f"[{s('H3.meta.ci_lo')}, {s('H3.meta.ci_hi')}] | {s('H3.meta.p')} | {s('H3.meta.p_adj')} | "
      f"{s('H3.meta.verdict')} |")
    a("")
    a(f"H2 detail: Spiegelhalter numerator {s('H2.PM.num')}, item-clustered bootstrap SE "
      f"{s('H2.PM.se')}; the analytic (unclustered) Z is {s('H2.PM.z_classic')} "
      f"(p {s('H2.PM.p_classic')}), shown descriptively.")
    a("")
    a(f"H3 guard (clean false-positive rate on `Q0_valid`): P {s('H3.meta.fpr_P')}, PM "
      f"{s('H3.meta.fpr_PM')}, change {s('H3.meta.fpr_delta')}; guard {s('H3.meta.guard')}.")
    a("")
    a("## Per-class detection next to the deterministic predicate baseline")
    a("")
    a("Detection is the fraction of the class's items whose own class question has a majority "
      "`yes` over 3 repeats (and, second column, whose `Q0_valid` has a majority `no`), with "
      "Wilson 95% intervals. The predicate column is `load_spec()` at `verif=\"PAG\"` at the pin; "
      "`uncovered` means no PAG constraint targets the class, which is not a miss. The last "
      "column is quoted from the sibling's H2 critic (different protocol; context only).")
    a("")
    for cond in CONDITIONS:
        a(f"### {COND_NAME[cond]}")
        a("")
        a("| class | channel | Jev: own class question | Jev: `Q0_valid` = no | predicate: class | "
          "predicate: any constraint | sibling H2 critic (quoted) |")
        a("|---|---|---|---|---|---|---|")
        for c in CLASSES:
            q = question_for_class(c)
            a(f"| {c} | {CHANNEL_OF[c]} | {rate(f'detect.{cond}.{c}.{q}')} | "
              f"{rate(f'detect.{cond}.{c}.Q0_valid')} | {s(f'baseline.predicate.{c}.{q}.rate')} | "
              f"{s(f'baseline.predicate.{c}.Q0_valid.rate')} | {s(f'baseline.ladder.h2critic.{c}')} |")
        a("")
    a(f"Predicate baseline classes uncovered at the pin: {s('baseline.predicate.uncovered')} "
      f"({s('baseline.predicate.n_constraints_pag')} PAG constraints).")
    a("")
    a("## Clean false-positive rates (100 clean items)")
    a("")
    a("| question | Jev P | Jev PM | predicate |")
    a("|---|---|---|---|")
    a(f"| `Q0_valid` majority no | {rate('fpr.P.Q0_valid')} | {rate('fpr.PM.Q0_valid')} | "
      f"{rate('baseline.predicate.fpr.Q0_valid')} |")
    for q in CLASS_QUESTIONS:
        a(f"| `{q}` majority yes | {rate(f'fpr.P.{q}')} | {rate(f'fpr.PM.{q}')} | "
          f"{s(f'baseline.predicate.fpr.{q}.rate')} |")
    a(f"| any class question majority yes | {rate('fpr.P.any_class')} | {rate('fpr.PM.any_class')} | |")
    a("")
    a("## Calibration")
    a("")
    a("Brier score over every valid individual answer (`p_yes = noul`), and Brier skill score "
      "against a constant predictor at each question's empirical base rate. Channel scopes pool "
      "the four class questions of that channel.")
    a("")
    a("| scope | Brier P | BSS P | n P | Brier PM | BSS PM | n PM |")
    a("|---|---|---|---|---|---|---|")
    for name in ("all", *QUESTION_IDS, "channel_metadata", "channel_payload"):
        a(f"| {name} | {s(f'brier.P.{name}')} | {s(f'bss.P.{name}')} | {s(f'brier.P.{name}.n')} | "
          f"{s(f'brier.PM.{name}')} | {s(f'bss.PM.{name}')} | {s(f'brier.PM.{name}.n')} |")
    a("")
    for cond in CONDITIONS:
        a(f"Reliability, {COND_NAME[cond]} (ECE {s(f'reliability.{cond}.ece')}):")
        a("")
        a("| bin of p_yes | count | mean p_yes | observed yes | Wilson 95% |")
        a("|---|---|---|---|---|")
        for b in range(10):
            pre = f"reliability.{cond}.b{b}"
            lo, hi = b / 10, (b + 1) / 10
            label = f"[{lo:.1f}, {hi:.1f}{']' if b == 9 else ')'}"
            a(f"| {label} | {s(pre + '.n')} | {s(pre + '.mean_p')} | {s(pre + '.obs')} | "
              f"[{s(pre + '.lo')}, {s(pre + '.hi')}] |")
        a("")
    a("## Agreement across repeats (Fleiss' kappa; categories yes / no / invalid)")
    a("")
    a("| question | P | PM |")
    a("|---|---|---|")
    for q in QUESTION_IDS:
        a(f"| `{q}` | {s(f'kappa.P.{q}')} | {s(f'kappa.PM.{q}')} |")
    a("")
    a("## Validity, latency and cost")
    a("")
    a("| measure | P | PM |")
    a("|---|---|---|")
    a(f"| invalid answer rate | {s('invalid.P')} | {s('invalid.PM')} |")
    a(f"| invalid answers | {s('invalid.P.answers')} | {s('invalid.PM.answers')} |")
    a(f"| calls with all answers invalid | {s('invalid.P.calls_all_invalid')} | {s('invalid.PM.calls_all_invalid')} |")
    a(f"| calls with some answers invalid | {s('invalid.P.calls_partial')} | {s('invalid.PM.calls_partial')} |")
    a(f"| calls re-requested (malformed or 422) | {s('latency.P.calls_rerequested')} | {s('latency.PM.calls_rerequested')} |")
    a(f"| calls with adapter retries (flagged) | {s('latency.P.calls_with_retries')} | {s('latency.PM.calls_with_retries')} |")
    for kind, label in (("attempt", "per attempt"), ("call", "per call incl. backoff")):
        for st in ("median", "p90", "p99", "max"):
            a(f"| latency {label}, {st} (s) | {s(f'latency.P.{kind}.{st}')} | {s(f'latency.PM.{kind}.{st}')} |")
        a(f"| latency {label}, n | {s(f'latency.P.{kind}.n')} | {s(f'latency.PM.{kind}.n')} |")
    a(f"| input tokens | {s('cost.P.input_tokens')} | {s('cost.PM.input_tokens')} |")
    a(f"| input tokens per call | {s('cost.P.input_tokens_per_call')} | {s('cost.PM.input_tokens_per_call')} |")
    a(f"| output tokens | {s('cost.P.output_tokens')} | {s('cost.PM.output_tokens')} |")
    a(f"| USD | {s('cost.P.usd')} | {s('cost.PM.usd')} |")
    a(f"| USD per call | {s('cost.P.usd_per_call')} | {s('cost.PM.usd_per_call')} |")
    a(f"| USD per item | {s('cost.P.usd_per_item')} | {s('cost.PM.usd_per_item')} |")
    a("")
    a(f"Total: {s('cost.total.input_tokens')} input tokens, {s('cost.total.output_tokens')} output "
      f"tokens, USD {s('cost.total.usd')} ({s('cost.total.usd_per_call')} per call, "
      f"{s('cost.total.usd_per_item')} per item) over {s('cost.attempts')} HTTP attempts, at USD "
      f"{s('cost.price_usd_per_1e9_input')} per 1e9 input tokens, output free.")
    a("")
    a("## Flat Ladder, quoted from the sibling paper (context only, no test)")
    a("")
    a("| rung | metadata-borne ADR | explicit DQ flag fraction | behavioral marker AUC |")
    a("|---|---|---|---|")
    for rung in ("haiku-4-5", "sonnet-5", "opus-4-8", "fable-5"):
        a(f"| {rung} | {s(f'baseline.ladder.{rung}.adr')} | {s(f'baseline.ladder.{rung}.flag_fraction')} | "
          f"{s(f'baseline.ladder.{rung}.marker_auc')} |")
    a("")
    a(f"Endpoint difference {s('baseline.ladder.endpoint_diff')} (95% CI "
      f"[{s('baseline.ladder.endpoint_ci_lo')}, {s('baseline.ladder.endpoint_ci_hi')}]), trend "
      f"{s('baseline.ladder.trend_per_tier')} per tier. Sibling H2 payload-only critic, "
      f"metadata-borne channel mean {s('baseline.ladder.h2critic.metadata_mean')}.")
    a("")
    a("## Secondary analyses (not part of the primary family)")
    a("")
    a("H1 per metadata-borne class, condition PM (Holm within the four):")
    a("")
    a("| class | d | chance | difference | 95% CI | p | Holm-4 p |")
    a("|---|---|---|---|---|---|---|")
    for c in METADATA_BORNE:
        p = f"H1.PM.{c}"
        a(f"| {c} | {s(p + '.d')} | {s(p + '.chance')} | {s(p + '.estimate')} | "
          f"[{s(p + '.ci_lo')}, {s(p + '.ci_hi')}] | {s(p + '.p')} | {s(p + '.p_holm4')} |")
    a("")
    a(f"H1 pooled in condition P: d {s('H1.P.pooled.d')} vs chance {s('H1.P.pooled.chance')}, "
      f"difference {s('H1.P.pooled.estimate')} [{s('H1.P.pooled.ci_lo')}, {s('H1.P.pooled.ci_hi')}], "
      f"p {s('H1.P.pooled.p')}: {s('H1.P.pooled.verdict')}.")
    a("")
    a("H2 in other scopes (unadjusted p):")
    a("")
    a("| scope | Spiegelhalter Z | p | BSS | BSS 95% CI | reading |")
    a("|---|---|---|---|---|---|")
    for sc in ("P", "PM.channel_metadata", "PM.channel_payload", "P.channel_metadata", "P.channel_payload"):
        p = f"H2.{sc}"
        a(f"| {sc} | {s(p + '.z')} | {s(p + '.p')} | {s(p + '.bss')} | [{s(p + '.bss_lo')}, "
          f"{s(p + '.bss_hi')}] | {s(p + '.verdict')} |")
    a("")
    a("H3 in other scopes (exact McNemar, unadjusted):")
    a("")
    a("| scope | PM rate | P rate | b | c | difference | 95% CI | p | reading |")
    a("|---|---|---|---|---|---|---|---|---|")
    for sc, label in (("all", "all 200 corrupted, own class question"), ("Q0", "all 200 corrupted, `Q0_valid` = no")):
        p = f"H3.{sc}"
        a(f"| {label} | {s(p + '.pm_rate')} | {s(p + '.p_rate')} | {s(p + '.b')} | {s(p + '.c')} | "
          f"{s(p + '.estimate')} | [{s(p + '.ci_lo')}, {s(p + '.ci_hi')}] | {s(p + '.p')} | "
          f"{s(p + '.verdict')} |")
    a("")
    a("Everything outside the primary table is descriptive or secondary, as registered.")
    a("")
    return "\n".join(L)


def main() -> int:
    TEMPLATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    TEMPLATE_PATH.write_text(build(), encoding="utf-8")
    print(f"template: wrote {TEMPLATE_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
