"""Generates results/jev-v2.template.md: every number in it is a named {{slot}} (§11).

    python -m jev_probe.template_v2   # (re)write the committed template
"""

from __future__ import annotations

import sys

from jev_probe.constants_v2 import API_ARMS, ARM_LABEL, ARMS, NOISE_LEVELS, TEMPLATE_PATH

NOISE_NAME = {"n00": "0%", "n10": "10%", "n30": "30%"}


def s(name: str) -> str:
    return "{{" + name + "}}"


def cp(prefix: str) -> str:
    return f"{s(prefix + '.rate')} [{s(prefix + '.lo')}, {s(prefix + '.hi')}] ({s(prefix + '.k')}/{s(prefix + '.n')})"


def build() -> str:
    L: list[str] = []
    a = L.append
    noises = [k for k, _ in NOISE_LEVELS]
    a("# jev-v2 results: sensing a non-observable contract field for a deterministic authority gate")
    a("")
    a("> Generated by `python -m jev_probe.analysis_v2` from the committed raw-response cache "
      "`responses/jev-v2.jsonl` and the frozen thresholds `results/jev-v2.tau.json`. Every number "
      "below is a named slot filled by that command; none is entered by hand. Registration: "
      "`prereg/jev-v2.md` (tag `prereg-jev-v2-reg`). Departures: `prereg/DEVIATIONS.md`.")
    a("")
    a("**Invariant.** Each sensor only proposed a value for `approval_token`. Its score was mapped "
      "to true / false / unknown by thresholds frozen on the validation split, unknown routed to "
      "deny, and the verdict was always computed by the sibling's deterministic loss predicates.")
    a("")
    a("## Run")
    a("")
    a("| field | value |")
    a("|---|---|")
    rows = [("status", "run.status"), ("hypotheses evaluated", "run.hypotheses_evaluated"),
            ("run segments", "run.n_segments")]
    rows += [(f"records cached, {ARM_LABEL[arm]}", f"run.n_calls.{arm}") for arm in ARMS]
    rows += [("HTTP attempts", "run.n_attempts"), ("adapter retries", "run.n_retries"),
             ("spend, USD (all arms)", "run.spend_usd"),
             ("returned model string(s), A", "run.model_versions.jev"),
             ("returned model string(s), B", "run.model_versions.llm"),
             ("MODEL_VERSION_CHANGED", "run.model_version_changed"),
             ("typesafe-sdk", "run.sdk.jev"), ("anthropic SDK", "run.sdk.llm"),
             ("engine pin (sarc-authority-derivation)", "run.pin.sarc_authority_derivation"),
             ("prereg commit", "run.prereg_commit"), ("generator SHA-256", "run.generator_sha256"),
             ("Jev context SHA-256", "run.jev_context_sha256"), ("Jev question SHA-256", "run.jev_question_sha256"),
             ("LLM prompt SHA-256", "run.llm_prompt_sha256"), ("thresholds file SHA-256", "run.tau_sha256")]
    for label, key in rows:
        a(f"| {label} | {s(key)} |")
    a(f"| bootstrap | {s('analysis.bootstrap_b')} resamples, seed {s('analysis.bootstrap_seed')} |")
    a("")
    a("Design facts, recomputed from the pin and the seeds:")
    a("")
    a("| split | items | true valid | true allow | approval-sensitive |")
    a("|---|---|---|---|---|")
    for split in ("validation", "test"):
        a(f"| {split} | {s(f'design.{split}.items')} | {s(f'design.{split}.valid')} | "
          f"{s(f'design.{split}.allow')} | {s(f'design.{split}.sensitive')} |")
    a("")
    a(f"Approval-sensitive tuples in the population: {s('design.population_sensitive')}.")
    a("")
    a("## Frozen thresholds (validation split, false-positive ceiling 1%)")
    a("")
    a("| arm | tau_true | tau_false | validation records | recomputation matches |")
    a("|---|---|---|---|---|")
    for arm in ARMS:
        a(f"| {ARM_LABEL[arm]} | {s(f'tau.{arm}.true')} | {s(f'tau.{arm}.false')} | "
          f"{s(f'tau.{arm}.n_validation')} | {s(f'tau.{arm}.recomputed_match')} |")
    a("")
    a("## Primary hypotheses (Holm over H1, H2, H3; two-sided, alpha 0.05)")
    a("")
    a("| hypothesis | estimate | 95% CI | p | Holm-adjusted p | verdict |")
    a("|---|---|---|---|---|---|")
    a(f"| H1: Jev verdict-change rate at 0% noise below 2% | {s('H1.estimate')} "
      f"({s('H1.k')}/{s('H1.n')}) | [{s('H1.ci_lo')}, {s('H1.ci_hi')}] | {s('H1.p')} | "
      f"{s('H1.p_adj')} | {s('H1.verdict')} |")
    a(f"| H2: Jev not worse than LLM at 30% noise | Jev {s('H2.jev_rate')} vs LLM {s('H2.llm_rate')}; "
      f"difference {s('H2.estimate')} (b = {s('H2.b')}, c = {s('H2.c')}, n = {s('H2.n')}) | "
      f"[{s('H2.ci_lo')}, {s('H2.ci_hi')}] | {s('H2.p')} | {s('H2.p_adj')} | {s('H2.verdict')} |")
    a(f"| H3: Jev cost per verdict below LLM | Jev USD {s('H3.jev_usd')} vs LLM USD {s('H3.llm_usd')}; "
      f"difference {s('H3.estimate')} (n = {s('H3.n')}) | [{s('H3.ci_lo')}, {s('H3.ci_hi')}] | "
      f"{s('H3.p')} | {s('H3.p_adj')} | {s('H3.verdict')} |")
    a("")
    a("## Verdict change (test split, Clopper-Pearson 95%)")
    a("")
    for arm in ARMS:
        a(f"### {ARM_LABEL[arm]}")
        a("")
        a("| noise | verdict-change rate | unsafe (deny to allow) | fail-closed (allow to deny) | "
          "approval-sensitive stratum | true-allow stratum | caused by misreading | caused by unknown |")
        a("|---|---|---|---|---|---|---|---|")
        for n in noises:
            p = f"{arm}.{n}"
            a(f"| {NOISE_NAME[n]} | {cp(f'vcr.{p}')} | {cp(f'vcr_unsafe.{p}')} | {cp(f'vcr_failclosed.{p}')} | "
              f"{cp(f'vcr_stratum.{p}.sensitive')} | {cp(f'vcr_stratum.{p}.allow')} | "
              f"{s(f'vcr_cause.{p}.misread')} | {s(f'vcr_cause.{p}.unknown')} |")
        a("")
    a("## Field error and abstention (test split, Wilson 95%)")
    a("")
    a("| arm | noise | field error, all | field error, perturbed | field error, unperturbed | "
      "abstention, all | abstention, perturbed | abstention, unperturbed |")
    a("|---|---|---|---|---|---|---|---|")
    for arm in ARMS:
        for n in noises:
            p = f"{arm}.{n}"
            a(f"| {ARM_LABEL[arm]} | {NOISE_NAME[n]} | {cp(f'field_error.{p}.all')} | "
              f"{cp(f'field_error.{p}.perturbed')} | {cp(f'field_error.{p}.unperturbed')} | "
              f"{cp(f'abstain.{p}.all')} | {cp(f'abstain.{p}.perturbed')} | {cp(f'abstain.{p}.unperturbed')} |")
    a("")
    a("Registered expectation (descriptive, not tested): abstention rises with noise for arms A and B.")
    a("")
    a("## Calibration of raw scores (test split)")
    a("")
    a("| arm | scope | Brier | ECE |")
    a("|---|---|---|---|")
    for arm in ARMS:
        for scope in ("all", *noises):
            label = "all noise levels" if scope == "all" else NOISE_NAME[scope]
            a(f"| {ARM_LABEL[arm]} | {label} | {s(f'brier.{arm}.{scope}')} | {s(f'ece.{arm}.{scope}')} |")
    a("")
    for arm in ARMS:
        a(f"Reliability, {ARM_LABEL[arm]}, all noise levels:")
        a("")
        a("| bin of score | count | mean score | observed valid | Wilson 95% |")
        a("|---|---|---|---|---|")
        for b in range(10):
            pre = f"reliability.{arm}.all.b{b}"
            lo, hi = b / 10, (b + 1) / 10
            label = f"[{lo:.1f}, {hi:.1f}{']' if b == 9 else ')'}"
            a(f"| {label} | {s(pre + '.n')} | {s(pre + '.mean_p')} | {s(pre + '.obs')} | "
              f"[{s(pre + '.lo')}, {s(pre + '.hi')}] |")
        a("")
    a("Per-noise reliability bins are in `results/jev-v2.slots.json` "
      "(`reliability.<arm>.<noise>.<bin>.*`).")
    a("")
    a("## Validity, latency, cost and input bytes (API arms, all records)")
    a("")
    a("| measure | " + " | ".join(ARM_LABEL[arm] for arm in API_ARMS) + " |")
    a("|---|" + "---|" * len(API_ARMS))

    def row(label: str, key: str) -> None:
        a(f"| {label} | " + " | ".join(s(key.format(arm=arm)) for arm in API_ARMS) + " |")

    row("invalid answers (after one re-request)", "invalid.{arm}")
    row("records re-requested", "latency.{arm}.calls_rerequested")
    row("records with adapter retries", "latency.{arm}.calls_with_retries")
    for kind, label in (("attempt", "per attempt"), ("call", "per record incl. backoff")):
        for st in ("median", "p90", "p99", "max"):
            row(f"latency {label}, {st} (s)", f"latency.{{arm}}.{kind}.{st}")
        row(f"latency {label}, n", f"latency.{{arm}}.{kind}.n")
    row("HTTP attempts", "cost.{arm}.attempts")
    row("input tokens", "cost.{arm}.input_tokens")
    row("output tokens", "cost.{arm}.output_tokens")
    row("USD", "cost.{arm}.usd")
    row("USD per attempt", "cost.{arm}.usd_per_call")
    row("USD per verdict", "cost.{arm}.usd_per_verdict")
    row("input bytes, total", "bytes.{arm}.total")
    row("input bytes per attempt", "bytes.{arm}.per_call")
    a("")
    a(f"Total spend across arms: USD {s('cost.total.usd')}. Arm C costs USD {s('cost.kw.usd')} and makes no call.")
    a("")
    a("Everything outside the primary table is descriptive or secondary, as registered.")
    a("")
    return "\n".join(L)


def main() -> int:
    TEMPLATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    TEMPLATE_PATH.write_text(build(), encoding="utf-8")
    print(f"template_v2: wrote {TEMPLATE_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
