#!/usr/bin/env python3
# Copyright 2026 SARC Suite Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
LaTeX release-kit gates for paper 6 (paper-tex/main.tex).

Ported with attribution from sarc-authority-derivation's paper-tex/gates/run_gates.py at the
engines.lock pin (commit cfb321e), itself ported from sarc-suite-one-pass's
paper-tex/gates/run_gates.py (commit 782261e). Apache-2.0; the sibling's licence is copied as
paper-tex/LICENSE-sarc-authority-derivation.

What is kept from the sibling, unchanged in mechanism: G1 (compiler-aware build, multi-pass
convergence, byte-identical double build under a fixed SOURCE_DATE_EPOCH, "??" ground-truth
check, overfull boxes above 10pt), G2's token list, the text-extraction helpers (bibliography
trim, page-footer and running-header stripping, dehyphenation, number-word normalisation,
ligature table), NUMBER_RE, G4's manuscript-sha sampling, G8's placeholder pattern and G9's
bibliography schema checks.

What paper 6 changes, and why:

- The source. Paper 5's main.tex was hand-typeset from its manuscript; paper 6's main.tex is
  generated by pandoc from paper/paper6-draft-v0.1-populated.md (paper-tex/build_main_tex.py),
  so the parity gates compare a manuscript with its own mechanical rendering.
- G1 also fails on XeTeX "Missing character" warnings (a glyph the font lacks renders as
  nothing, silently).
- G2 also forbids an unfilled slot ("{{"), an unresolved pandoc citation ("[@") and "TODO".
- G3 checks numbers both ways (Phase D brief §6): every number in a slot the manuscript uses
  appears in the PDF; and every number left in the PDF body, after the structural and
  registered-parameter allowlist of lint/typed_numerals.py, is a number some used slot
  carries. Slots come from paper/populate.py's build_slots(), the same function that fills the
  manuscript.
- G4 anchors on paper 6's section titles and reads the title, author and affiliation from the
  manuscript's YAML front matter.
- G5 counts paper 6's structural elements: top-level sections, tables, figures and the bold
  proposition lead-ins.
- G6 checks paper 6's own disclosure sentences.
- G7: the sidecars are generated from the manuscript (paper-tex/make_sidecars.py); the gate
  regenerates them and requires byte equality.
- G8 also requires every pandoc citation key to be a verified-citations.json id and every
  verified citation to be cited.
- G9 reads the bibliography audit from paper-tex/bib-audit.json (written by
  paper-tex/verify_citations.py) and requires a passing audit record for every citation.
- Four repository lints run as gate rows: terminology (lint/terminology.py), proof status
  (checkers/proof_status_lint.py), typed numerals (lint/typed_numerals.py) and populated-draft
  freshness (paper/populate.py --check).
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

GATES_DIR = Path(__file__).resolve().parent
PAPER_TEX_DIR = GATES_DIR.parent
REPO_ROOT = PAPER_TEX_DIR.parent

DRAFT_MD = REPO_ROOT / "paper" / "paper6-draft-v0.1.md"
SOURCE_MD = REPO_ROOT / "paper" / "paper6-draft-v0.1-populated.md"
MAIN_TEX = PAPER_TEX_DIR / "main.tex"
MAIN_PDF = PAPER_TEX_DIR / "main.pdf"
REPORT_PATH = PAPER_TEX_DIR / "parity-report.json"
REFS_BIB = PAPER_TEX_DIR / "refs.bib"
CITATIONS_JSON = REPO_ROOT / "verified-citations.json"
BIB_AUDIT_JSON = PAPER_TEX_DIR / "bib-audit.json"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# Paper 6's numbered sections (brief §4, items 2 to 12), as LaTeX numbers them. The abstract,
# the acknowledgements (unnumbered) and the two appendices sit outside this list.
SECTION_TITLES = [
    "1 Introduction",
    "2 Setting",
    "3 Invariants",
    "4 Propositions",
    "5 Admission policy and estimation",
    "6 Experimental design",
    "7 Results",
    "8 Related work and fence",
    "9 Claims versus non-claims",
    "10 Limitations",
    "11 Reproducibility",
]


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, check=False, **kwargs)


# ---------------------------------------------------------------------------
# G1: Build (ported; adds the XeTeX missing-character check)
# ---------------------------------------------------------------------------

COMPILER_ENV_VAR = "SARC_LATEX_COMPILER"
MAX_PASSES = 4

UNDEFINED_REF_RE = re.compile(r"LaTeX Warning: Reference `([^']*)' on page \d+ undefined")
UNDEFINED_CITE_RE = re.compile(r"LaTeX Warning: Citation `([^']*)' .*undefined")
MISSING_CHAR_RE = re.compile(r"Missing character: There is no (.+?) in font")
OVERFULL_PATTERNS = {
    "latexmk": re.compile(r"Overfull \\hbox \(([\d.]+)pt too wide\) in paragraph at lines (\d+)--(\d+)"),
    "tectonic": re.compile(r"warning: [^:\s]+:(\d+): Overfull \\hbox \(([\d.]+)pt too wide\)"),
}
GENERATED_FILE_GLOBS = [
    "main.pdf", "main.log", "main.aux", "main.bbl", "main.blg",
    "main.out", "main.fls", "main.fdb_latexmk", "main.synctex.gz",
    "main.toc", "texput.log",
]

# Content-stable epoch, the sibling's constant reused verbatim (its own comment: an already
# established "before any result existed" reference point is not this repository's to
# reinvent). Also used by build_main_tex.py and make_arxiv_tarball.py.
SOURCE_DATE_EPOCH = "1786609963"


def _source_date_epoch() -> str:
    return SOURCE_DATE_EPOCH


def _reproducible_build_env() -> dict:
    env = dict(os.environ)
    env["SOURCE_DATE_EPOCH"] = _source_date_epoch()
    env["TZ"] = "UTC"
    return env


def _sha256_file(path: Path):
    if not path.exists():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _detect_compiler() -> str:
    forced = os.environ.get(COMPILER_ENV_VAR, "").strip().lower()
    if forced:
        return forced
    if shutil.which("tectonic"):
        return "tectonic"
    if shutil.which("latexmk"):
        return "latexmk"
    return ""


def _clean_generated() -> None:
    for name in GENERATED_FILE_GLOBS:
        f = PAPER_TEX_DIR / name
        if f.exists():
            f.unlink()


def _pdf_page_count(pdf_path: Path):
    if not pdf_path.exists():
        return None
    r = run(["pdfinfo", str(pdf_path)])
    m = re.search(r"^Pages:\s+(\d+)", r.stdout, re.MULTILINE)
    return int(m.group(1)) if m else None


def _pdf_unresolved_marker_count(pdf_path: Path) -> int:
    """Ground truth on the rendered PDF: LaTeX prints "??" for an unresolved \\ref or \\cite."""
    if not pdf_path.exists():
        return -1
    r = run(["pdftotext", str(pdf_path), "-"])
    return (r.stdout or "").count("??")


def _run_compiler_once(compiler: str) -> tuple[int, str]:
    env = _reproducible_build_env()
    if compiler == "tectonic":
        r = run(["tectonic", "--print", "main.tex"], cwd=str(PAPER_TEX_DIR), env=env)
    elif compiler == "latexmk":
        r = run(["latexmk", "-pdf", "-interaction=nonstopmode", "main.tex"], cwd=str(PAPER_TEX_DIR), env=env)
    else:
        raise RuntimeError(f"unsupported compiler {compiler!r}")
    return r.returncode, f"{r.stdout or ''}\n{r.stderr or ''}"


def _parse_build_diagnostics(compiler: str, output: str) -> dict:
    errors = [line for line in output.splitlines() if line.startswith("! ")]
    overfull = []
    pattern = OVERFULL_PATTERNS[compiler]
    for m in pattern.finditer(output):
        if compiler == "tectonic":
            pts, where = float(m.group(2)), {"line": m.group(1)}
        else:
            pts, where = float(m.group(1)), {"lines": f"{m.group(2)}--{m.group(3)}"}
        if pts > 10.0:
            overfull.append({"pt": pts, **where})
    return {
        "errors": errors,
        "undefined_references": UNDEFINED_REF_RE.findall(output),
        "undefined_citations": UNDEFINED_CITE_RE.findall(output),
        "missing_characters": sorted(set(MISSING_CHAR_RE.findall(output))),
        "overfull_hbox_above_10pt": overfull,
    }


def _do_one_build(compiler: str) -> dict:
    """A clean start, then the compiler rerun (up to MAX_PASSES) until references converge."""
    _clean_generated()
    passes = []
    for _ in range(MAX_PASSES):
        rc, output = _run_compiler_once(compiler)
        diagnostics = _parse_build_diagnostics(compiler, output)
        passes.append({"exit_code": rc, **diagnostics})
        if rc != 0:
            break
        if not diagnostics["undefined_references"] and not diagnostics["undefined_citations"]:
            break
    latest = passes[-1]
    return {
        "exit_code": latest["exit_code"],
        "pdf_produced": MAIN_PDF.exists(),
        "page_count": _pdf_page_count(MAIN_PDF),
        "file_list": sorted(p.name for p in PAPER_TEX_DIR.glob("main.*")),
        "pdf_sha256": _sha256_file(MAIN_PDF),
        "passes_needed": len(passes),
        "errors": latest["errors"],
        "undefined_references": latest["undefined_references"],
        "undefined_citations": latest["undefined_citations"],
        "missing_characters": latest["missing_characters"],
        "overfull_hbox_above_10pt": latest["overfull_hbox_above_10pt"],
        "pdf_unresolved_marker_count": _pdf_unresolved_marker_count(MAIN_PDF),
    }


def gate_g1_build() -> dict:
    compiler = _detect_compiler()
    if not compiler:
        return {"pass": False,
                "detail": f"no supported LaTeX compiler on PATH; install Tectonic or latexmk, or set {COMPILER_ENV_VAR}"}
    builds = [_do_one_build(compiler), _do_one_build(compiler)]
    latest = builds[-1]
    exit_code_zero = all(b["exit_code"] == 0 for b in builds)
    pdf_produced = all(b["pdf_produced"] for b in builds)
    two_build_identical = (
        builds[0]["page_count"] is not None
        and builds[0]["page_count"] == builds[1]["page_count"]
        and builds[0]["file_list"] == builds[1]["file_list"]
        and builds[0]["pdf_sha256"] is not None
        and builds[0]["pdf_sha256"] == builds[1]["pdf_sha256"]
    )
    no_diagnostics = (
        not latest["errors"]
        and latest["pdf_unresolved_marker_count"] == 0
        and not latest["overfull_hbox_above_10pt"]
        and not latest["missing_characters"]
    )
    return {
        "pass": exit_code_zero and pdf_produced and two_build_identical and no_diagnostics,
        "compiler": compiler,
        "source_date_epoch": _source_date_epoch(),
        "exit_code_zero": exit_code_zero,
        "pdf_produced": pdf_produced,
        "two_build_identical": two_build_identical,
        "pdf_sha256": latest["pdf_sha256"],
        "page_count": latest["page_count"],
        "file_list": latest["file_list"],
        "builds": builds,
        "errors": latest["errors"],
        "missing_characters": latest["missing_characters"],
        "pdf_unresolved_marker_count": latest["pdf_unresolved_marker_count"],
        # Reported, not gated (the sibling's reasoning): Tectonic logs these from internal
        # sub-passes even when the rendered PDF, checked above, is fully resolved.
        "compiler_log_undefined_references": latest["undefined_references"],
        "compiler_log_undefined_citations": latest["undefined_citations"],
        "overfull_hbox_above_10pt": latest["overfull_hbox_above_10pt"],
    }


# ---------------------------------------------------------------------------
# G2: Token purity (ported list, plus paper 6's slot and citation syntax)
# ---------------------------------------------------------------------------

def gate_g2_token_purity() -> dict:
    tex = MAIN_TEX.read_text(encoding="utf-8")
    forbidden = {
        "**": tex.count("**"),
        "```": tex.count("```"),
        "[GENERATED": tex.count("[GENERATED"),
        "{{": tex.count("{{"),
        "[@": tex.count("[@"),
        "TODO": tex.count("TODO"),
    }
    hits = {k: v for k, v in forbidden.items() if v}
    return {"pass": not hits, "forbidden_token_counts": forbidden, "cite_needed_placeholder_count": tex.count("[CITE")}


# ---------------------------------------------------------------------------
# Shared text extraction helpers (ported unchanged in mechanism)
# ---------------------------------------------------------------------------

def _trim_bibliography(text: str) -> str:
    """Everything from the References heading on is bibtex output, not manuscript prose.

    Paper 6 keeps its appendices before the bibliography, so they stay in."""
    m = re.search(r"[\n\x0c]\s*References\s*[\n\x0c]", text)
    return text[:m.start()] if m else text


def _strip_page_footers(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if not re.fullmatch(r"\s*\d+\s*", line))


def _strip_repeated_page_furniture(text: str) -> str:
    """Remove a running header: a first line repeated on at least half the pages (positional)."""
    pages = text.split("\x0c")
    if len(pages) < 3:
        return text
    first_lines = []
    for p in pages:
        candidates = [line for line in p.splitlines() if line.strip()]
        first_lines.append(candidates[0].strip() if candidates else None)
    threshold = max(3, len(pages) // 2)
    furniture = {line for line, n in Counter(x for x in first_lines if x is not None).items() if n >= threshold}
    if not furniture:
        return text
    out_pages = []
    for p in pages:
        lines = p.splitlines()
        idx = next((i for i, line in enumerate(lines) if line.strip()), None)
        if idx is not None and lines[idx].strip() in furniture:
            lines = lines[:idx] + lines[idx + 1:]
        out_pages.append("\n".join(lines))
    return "\x0c".join(out_pages)


def extract_pdf_text() -> str:
    """Layout extraction, running header and bibliography removed, page footers stripped (G3)."""
    r = run(["pdftotext", "-layout", str(MAIN_PDF), "-"])
    text = _strip_repeated_page_furniture(r.stdout)
    text = _trim_bibliography(text)
    return _strip_page_footers(text)


def extract_pdf_text_reflow() -> str:
    """Reflowed extraction of the full document (G6)."""
    r = run(["pdftotext", str(MAIN_PDF), "-"])
    return _strip_page_footers(_strip_repeated_page_furniture(r.stdout))


def extract_pdf_text_layout_full() -> str:
    """Layout extraction of the full document, page footers stripped (G4)."""
    r = run(["pdftotext", "-layout", str(MAIN_PDF), "-"])
    return _strip_page_footers(_strip_repeated_page_furniture(r.stdout))


def md_body(path: Path = SOURCE_MD) -> str:
    """The manuscript without its YAML front matter."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---\n"):
        text = text[text.index("\n---\n", 4) + 5:]
    return text


def md_front_matter(path: Path = SOURCE_MD) -> dict:
    import yaml

    text = path.read_text(encoding="utf-8")
    return yaml.safe_load(text[4:text.index("\n---\n", 4)]) if text.startswith("---\n") else {}


def md_plain(numbered: bool = False) -> str:
    numbering = ["--lua-filter", str(PAPER_TEX_DIR / "filters" / "number-sections.lua")]
    cmd = ["pandoc", "-f", "markdown", "-t", "plain", "--wrap=none"] + (numbering if numbered else [])
    return run(cmd, input=md_body()).stdout


NUMBER_RE = re.compile(
    r"\b\d{1,3}(?:,\d{3})+(?:\.\d+)?(?!\d)"    # 15,120 / 27,000
    r"|\b\d+\.\d+(?:[eE][-+]?\d+)?(?!\d)"      # 6.124 / 1.69e-21
    r"|\b\d+[eE][-+]?\d+(?!\d)"                # bare scientific notation
    r"|\b\d+(?!\d)"                            # plain integers
)


def dehyphenate(text: str) -> str:
    text = re.sub(r"-\n\s*(?=[a-z])", "-", text)
    return re.sub(r"([eE][-+])\n\s*(?=\d)", r"\1", text)


def extract_numbers(text: str) -> Counter:
    return Counter(NUMBER_RE.findall(dehyphenate(text)))


_ONES = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
    "eleven": 11, "twelve": 12, "thirteen": 13, "fourteen": 14, "fifteen": 15,
    "sixteen": 16, "seventeen": 17, "eighteen": 18, "nineteen": 19,
}
_TENS = {"twenty": 20, "thirty": 30, "forty": 40, "fifty": 50, "sixty": 60, "seventy": 70, "eighty": 80, "ninety": 90}
_SCALES = {"hundred": 100, "thousand": 1000, "million": 1000000}
_NUMBER_WORDS = set(_ONES) | set(_TENS) | set(_SCALES)
_WORD_ALT = "|".join(sorted(_NUMBER_WORDS, key=len, reverse=True))
_NUMBER_WORD_RUN_RE = re.compile(rf"\b(?:{_WORD_ALT})(?:[\s-]+(?:{_WORD_ALT}))*\b", re.IGNORECASE)


def _number_words_to_int(words: list[str]) -> int:
    total = current = 0
    for w in (x.lower() for x in words):
        if w in _ONES:
            current += _ONES[w]
        elif w in _TENS:
            current += _TENS[w]
        elif w == "hundred":
            current = (current or 1) * 100
        elif w in ("thousand", "million"):
            total += (current or 1) * _SCALES[w]
            current = 0
    return total + current


# Font and extraction artifacts, not content (ported table).
_QUOTE_NORMALIZE = {
    "‘": "'", "’": "'", "“": '"', "”": '"', "∗": "*", "′": "'", "–": "--",
    "ﬀ": "ff", "ﬁ": "fi", "ﬂ": "fl", "ﬃ": "ffi", "ﬄ": "ffl", "−": "-",
}


def normalize_number_words(text: str) -> str:
    for uni, ascii_ in _QUOTE_NORMALIZE.items():
        text = text.replace(uni, ascii_)

    def repl(m: re.Match) -> str:
        n = _number_words_to_int(re.split(r"[\s-]+", m.group(0)))
        return f"{n:,}" if n >= 1000 else str(n)

    return _NUMBER_WORD_RUN_RE.sub(repl, text)


# ---------------------------------------------------------------------------
# G3: Number parity, both directions (Phase D brief §6)
# ---------------------------------------------------------------------------

TAG_PHRASES = ["machine-checked", "checked-scope-only", "pending-human-review"]


def _load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, str(path))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def used_slots() -> dict[str, str]:
    """The slots the manuscript actually uses, with their values (paper/populate.py)."""
    populate = _load_module("paper6_populate", REPO_ROOT / "paper" / "populate.py")
    return populate.used_slot_values(DRAFT_MD.read_text(encoding="utf-8"))


def _slot_numbers(slots: dict[str, str]) -> dict[str, list[str]]:
    by_number: dict[str, list[str]] = {}
    for name, value in slots.items():
        for tok in NUMBER_RE.findall(normalize_number_words(str(value))):
            by_number.setdefault(tok, []).append(name)
    return by_number


def _verbatim_numbers(md_text: str) -> set[str]:
    """Numbers inside the manuscript's code spans, code blocks and quotations: verbatim registered
    text (prompts, question wording, banks), which the PDF prints as ordinary text."""
    spans = re.findall(r"```.*?```|`[^`\n]*`|\"[^\"\n]*\"", md_text, re.DOTALL)
    return {n for s in spans for n in NUMBER_RE.findall(s)}


def gate_g3_number_parity() -> dict:
    typed_numerals = _load_module("typed_numerals", REPO_ROOT / "lint" / "typed_numerals.py")
    raw_pdf = dehyphenate(extract_pdf_text())
    for uni, ascii_ in _QUOTE_NORMALIZE.items():
        raw_pdf = raw_pdf.replace(uni, ascii_)
    pdf_text = normalize_number_words(raw_pdf)
    pdf_numbers = set(NUMBER_RE.findall(pdf_text))
    slots = used_slots()
    slot_numbers = _slot_numbers(slots)

    # Forward: every number a used slot carries is printed somewhere in the paper (digits or
    # words).
    missing_from_pdf = {tok: names for tok, names in slot_numbers.items() if tok not in pdf_numbers}

    # Reverse: every digit number the PDF prints is a slot number, verbatim registered text, or
    # survives the typed-numerals allowlist (structural numbers, identifiers, registered design
    # parameters). Number words are not typed numerals and are not checked in this direction.
    verbatim = _verbatim_numbers(SOURCE_MD.read_text(encoding="utf-8"))
    residual = typed_numerals.residual_numbers(raw_pdf, pdf=True)
    unexplained_in_pdf = sorted({tok for tok in residual if tok not in slot_numbers and tok not in verbatim})

    md_text = SOURCE_MD.read_text(encoding="utf-8")
    tag_counts = {p: {"source_count": md_text.count(p), "pdf_count": pdf_text.count(p)} for p in TAG_PHRASES}
    tags_ok = all((v["pdf_count"] > 0) == (v["source_count"] > 0) for v in tag_counts.values())

    return {
        "pass": not missing_from_pdf and not unexplained_in_pdf and tags_ok,
        "used_slot_count": len(slots),
        "slot_number_count": len(slot_numbers),
        "slot_numbers_missing_from_pdf": missing_from_pdf,
        "pdf_numbers_not_in_slots_or_registered": unexplained_in_pdf,
        "tag_counts": tag_counts,
    }


# ---------------------------------------------------------------------------
# G4: Prose parity (ported design: section coverage band, front matter, sha-sampled sentences)
# ---------------------------------------------------------------------------

def normalize_ws(text: str) -> str:
    text = dehyphenate(text)
    text = text.replace("\u00ad", "")
    for uni, ascii_ in _QUOTE_NORMALIZE.items():
        text = text.replace(uni, ascii_)
    text = re.sub(r"'\s+([,)])", r"'\1", text)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s*_\s*", "_", text)
    text = re.sub(r"\s+\)", ")", text)
    text = re.sub(r"\s+:", ":", text)
    return text.strip()


def _slices(text: str, anchors: list[str], end_anchor: str | None) -> dict[str, str]:
    positions, search_from = [], 0
    for anchor in anchors + ([end_anchor] if end_anchor else []):
        idx = text.find(anchor, search_from)
        positions.append(idx)
        if idx != -1:
            search_from = idx + len(anchor)
    out = {}
    for pos, title in enumerate(anchors):
        start = positions[pos]
        end = next((p for p in positions[pos + 1:] if p != -1), None)
        out[title] = "" if start == -1 else (text[start:end] if end else text[start:])
    return out


def md_section_slices() -> dict[str, str]:
    """filters/number-sections.lua numbers the plain rendering exactly as LaTeX numbers the PDF."""
    return _slices(normalize_ws(md_plain(numbered=True)), SECTION_TITLES, "Acknowledgements")


def pdf_section_slices() -> dict[str, str]:
    return _slices(normalize_ws(extract_pdf_text_layout_full()), SECTION_TITLES, "Acknowledgements")


def word_count(text: str) -> int:
    return len(normalize_ws(text).split())


# The sibling widened this band to 15-160% for a hand-condensed main.tex. Paper 6's main.tex is
# a pandoc rendering, so the expected ratio is close to 100%; the band only absorbs extraction
# differences (table layout, math spacing, list markers).
SECTION_WORD_RATIO_MIN_PCT = 80.0
SECTION_WORD_RATIO_MAX_PCT = 125.0


def deterministic_sentence_indices(sentences: list[str], seed: str, k: int = 10) -> list[int]:
    n = len(sentences)
    if n == 0:
        return []
    idxs, i = [], 0
    while len(idxs) < min(k, n):
        cand = int(hashlib.sha256(f"{seed}:{i}".encode()).hexdigest(), 16) % n
        if cand not in idxs:
            idxs.append(cand)
        i += 1
    return sorted(idxs)


def split_sentences(text: str) -> list[str]:
    text = re.sub(r"(?m)^[ \t]*-[ \t]+", "\n\n", text)
    out = []
    for para in re.split(r"\n\s*\n", text):
        if re.search(r"[_^]|>=|<=|\bmax\b|\bmin\b|\bsum\b|[≤≥Σ∑]", para):
            continue
        if len(re.findall(r"  {2,}", para)) >= 2:
            continue
        para = normalize_ws(para)
        if not para:
            continue
        for s in re.split(r"(?<=[.!?])\s+(?=[A-Z(\[])", para):
            s = s.strip()
            if len(s) <= 20 or sum(c.isalpha() for c in s) / len(s) <= 0.5:
                continue
            if re.search(r"-{4,}", s):
                continue
            out.append(s)
    return out


def front_matter_check() -> dict:
    fm = md_front_matter()
    tex = MAIN_TEX.read_text(encoding="utf-8")
    title_m = re.search(r"\\title\{([^\n]*)\}", tex)
    author_m = re.search(r"\\author\{(.*?)\\thanks\{([^\n}]*)\}\}", tex)
    md_title = run(["pandoc", "-f", "markdown", "-t", "latex", "--wrap=none"], input=fm.get("title", "")).stdout.strip()
    checks = {
        "title": (md_title, title_m.group(1).strip() if title_m else ""),
        "author_name": (fm.get("author", ""), author_m.group(1).strip() if author_m else ""),
        "affiliation": (fm.get("thanks", ""), author_m.group(2).strip() if author_m else ""),
    }
    out = {k: {"md": a, "tex": b, "match": bool(a) and a == b} for k, (a, b) in checks.items()}
    return {"pass": all(v["match"] for v in out.values()), **out}


_IDENTIFIER_RE = re.compile(r"`[^`]+`|\bCH-?[A-Z]?\d+\b|\b[a-z_][a-z0-9_.-]*\.(?:py|json|jsonl|md)\b")


def _sentence_content_tokens(sentence: str) -> dict:
    return {"numbers": NUMBER_RE.findall(sentence),
            "identifiers": [i for i in (m.strip("`") for m in _IDENTIFIER_RE.findall(sentence)) if i]}


def gate_g4_prose_parity() -> dict:
    md_slices, pdf_slices = md_section_slices(), pdf_section_slices()
    sections, all_within = {}, True
    for title in SECTION_TITLES:
        md_wc, pdf_wc = word_count(md_slices.get(title, "")), word_count(pdf_slices.get(title, ""))
        pct = pdf_wc / md_wc * 100 if md_wc else None
        within = (pdf_wc == 0) if md_wc == 0 else SECTION_WORD_RATIO_MIN_PCT <= pct <= SECTION_WORD_RATIO_MAX_PCT
        all_within = all_within and within and md_wc > 0
        sections[title] = {"md_words": md_wc, "pdf_words": pdf_wc,
                           "pct_of_source": round(pct, 3) if pct is not None else None, "within_band": within}

    metadata = front_matter_check()
    sentences = split_sentences(md_plain())
    source_sha256 = hashlib.sha256(SOURCE_MD.read_bytes()).hexdigest()
    idxs = deterministic_sentence_indices(sentences, source_sha256, k=10)
    pdf_norm = normalize_ws(extract_pdf_text_layout_full())
    pdf_flat = pdf_norm.replace(" ", "")
    sample = []
    for i in idxs:
        s = sentences[i]
        tokens = _sentence_content_tokens(s)
        missing_numbers = [n for n in tokens["numbers"] if n not in pdf_norm]
        missing_ids = [x for x in tokens["identifiers"] if x.replace(" ", "") not in pdf_flat]
        sample.append({"index": i, "sentence": s[:160], **tokens, "missing_numbers": missing_numbers,
                       "missing_identifiers": missing_ids, "found": not missing_numbers and not missing_ids})
    ok = all_within and metadata["pass"] and all(r["found"] for r in sample)
    return {"pass": ok, "source_sha256": source_sha256,
            "section_word_ratio_band_pct": [SECTION_WORD_RATIO_MIN_PCT, SECTION_WORD_RATIO_MAX_PCT],
            "sections": sections, "front_matter_metadata_check": metadata, "sentence_sample": sample}


# ---------------------------------------------------------------------------
# G5: Structure parity
# ---------------------------------------------------------------------------

def gate_g5_structure_parity() -> dict:
    md = md_body()
    tex = MAIN_TEX.read_text(encoding="utf-8")
    md_counts = {
        "sections": len(re.findall(r"^# \S", md, re.MULTILINE)),
        "subsections": len(re.findall(r"^## \S", md, re.MULTILINE)),
        "tables": len(re.findall(r"^\|[\s:|-]+\|\s*$", md, re.MULTILINE)),
        "figures": len(re.findall(r"^!\[", md, re.MULTILINE)),
        "propositions": len(re.findall(r"\*\*(?:Proposition S\d|N6)\b", md)),
        "footnotes": len(re.findall(r"^\[\^\w+\]:", md, re.MULTILINE)) + (1 if md_front_matter().get("thanks") else 0),
    }
    tex_counts = {
        "sections": len(re.findall(r"^\\section\*?\{", tex, re.MULTILINE)),
        "subsections": len(re.findall(r"^\\subsection\*?\{", tex, re.MULTILINE)),
        "tables": len(re.findall(r"^\\begin\{longtable\}", tex, re.MULTILINE)),
        "figures": len(re.findall(r"\\includegraphics", tex)),
        "propositions": len(re.findall(r"\\textbf\{(?:Proposition S\d|N6)\b", tex)),
        "footnotes": len(re.findall(r"\\footnote\{", tex)) + len(re.findall(r"\\thanks\{", tex)),
    }
    counts = {k: {"source": md_counts[k], "tex": tex_counts[k], "equal": md_counts[k] == tex_counts[k]} for k in md_counts}
    return {"pass": all(v["equal"] for v in counts.values()), "counts": counts}


# ---------------------------------------------------------------------------
# G6: Disclosure and banners (paper 6's own sentences; must survive verbatim into the PDF)
# ---------------------------------------------------------------------------

DISCLOSURE_SENTENCES = {
    "ai_assistance": (
        "AI assistance was used for drafting and engineering, under the author's direction; "
        "the author is solely responsible for the content."
    ),
    "external_review": (
        "An external model review of the novelty fence was commissioned before registration, "
        "committed unedited and not applied; the author re-registered after reading it."
    ),
    "non_claim": (
        "Correctness is relative to the declared loss model, candidate representation and "
        "reachable states; all domains are constructed."
    ),
    "invariant": (
        "A model's output enters the gate as an observation with an admission policy. "
        "It never carries authority."
    ),
    "fence": (
        "This paper does not introduce abstention, calibration, conformal control or reducts. "
        "It shows how an abstaining sensor composes with a sufficiency-checked contract, bounds "
        "the resulting exposure by the contract's sensed fields, and selects contracts to "
        "minimise its estimated bound."  # round-two F2: was "minimise it" (NOVELTY.md's wording)
    ),
}


def gate_g6_disclosure_and_banners() -> dict:
    pdf_text = normalize_ws(extract_pdf_text_reflow())
    md_text = normalize_ws(md_plain())
    present = {k: {"in_manuscript": normalize_ws(v) in md_text, "in_pdf": normalize_ws(v) in pdf_text}
               for k, v in DISCLOSURE_SENTENCES.items()}
    return {"pass": all(v["in_manuscript"] and v["in_pdf"] for v in present.values()), "sentences": present}


# ---------------------------------------------------------------------------
# G7: arXiv sidecar sync (generated from the manuscript)
# ---------------------------------------------------------------------------

ARXIV_ABSTRACT_MAX_CHARS = 1920
ARXIV_ABSTRACT_REQUIRED_PHRASE = "admission policy"
ARXIV_METADATA_REQUIRED_AUTHOR_LINE = "Gaston Besanson (Universidad Torcuato Di Tella)"


def gate_g7_sidecar_sync() -> dict:
    sidecars = _load_module("make_sidecars", PAPER_TEX_DIR / "make_sidecars.py")
    expected = sidecars.expected()
    in_sync = {p.name: p.exists() and p.read_text(encoding="utf-8") == t for p, t in expected.items()}
    abstract = expected[sidecars.ABSTRACT_PATH]
    abstract_len = len(abstract.rstrip("\n"))
    abstract_words = len(abstract.split())
    checks = {
        "sidecars_match_generator": all(in_sync.values()),
        "abstract_within_max_chars": abstract_len <= ARXIV_ABSTRACT_MAX_CHARS,
        "abstract_at_most_200_words": abstract_words <= 200,
        "abstract_has_required_phrase": ARXIV_ABSTRACT_REQUIRED_PHRASE in abstract,
        "metadata_has_required_author_line": ARXIV_METADATA_REQUIRED_AUTHOR_LINE in expected[sidecars.METADATA_PATH],
    }
    return {"pass": all(checks.values()), **checks, "in_sync": in_sync,
            "abstract_char_count": abstract_len, "abstract_word_count": abstract_words}


# ---------------------------------------------------------------------------
# G8: Citation completeness
# ---------------------------------------------------------------------------

CITE_PLACEHOLDER_PATTERN = re.compile(r"\[CITE[-:][^\]]*\]")
PANDOC_CITE_RE = re.compile(r"@([A-Za-z0-9][A-Za-z0-9_:.-]*[A-Za-z0-9])")


def cited_keys(text: str) -> set[str]:
    keys = set()
    for group in re.findall(r"\[([^\]]*@[^\]]*)\]", text):
        keys.update(PANDOC_CITE_RE.findall(group))
    return keys


def gate_g8_citation_completeness() -> dict:
    text = SOURCE_MD.read_text(encoding="utf-8")
    placeholders = CITE_PLACEHOLDER_PATTERN.findall(text)
    verified = {c["id"] for c in json.loads(CITATIONS_JSON.read_text(encoding="utf-8"))["citations"]}
    keys = cited_keys(text)
    citation_check = _load_module("citation_check", PAPER_TEX_DIR / "citation_check.py")
    tokens = citation_check.check(str(SOURCE_MD), str(CITATIONS_JSON))
    unknown, uncited = sorted(keys - verified), sorted(verified - keys)
    return {"pass": not placeholders and not unknown and not uncited and tokens["clean"],
            "cite_placeholder_count": len(placeholders), "cite_placeholders": placeholders,
            "cited_keys": sorted(keys), "keys_not_verified": unknown, "verified_but_uncited": uncited,
            "citation_check_tokens_clean": tokens["clean"]}


# ---------------------------------------------------------------------------
# G9: Bibliography quality (ported schema checks; audit file per citation)
# ---------------------------------------------------------------------------

VALID_ENTRY_TYPES = {"article", "inproceedings", "incollection", "misc"}
REQUIRED_VENUE_FIELDS_BY_TYPE = {"article": ("journal",), "inproceedings": ("booktitle",), "incollection": ("booktitle",)}
TRUNCATED_AUTHOR_RE = re.compile(r"\bet al\b|\bothers\b|\.\.\.", re.IGNORECASE)


def gate_g9_bibliography_quality() -> dict:
    citations = json.loads(CITATIONS_JSON.read_text(encoding="utf-8"))["citations"]
    refs_bib_text = REFS_BIB.read_text(encoding="utf-8") if REFS_BIB.exists() else ""
    audit = json.loads(BIB_AUDIT_JSON.read_text(encoding="utf-8")) if BIB_AUDIT_JSON.exists() else {"results": []}
    audit_by_id = {r["id"]: r for r in audit.get("results", [])}
    problems: dict[str, list] = {k: [] for k in (
        "invalid_entry_type", "missing_authors", "truncated_author_list", "missing_venue_fields",
        "doi_mismatches", "misc_with_venue_info", "audit_missing", "audit_failed")}
    for c in citations:
        cid, entry_type = c.get("id", "<no id>"), c.get("entry_type")
        if entry_type not in VALID_ENTRY_TYPES:
            problems["invalid_entry_type"].append({"id": cid, "entry_type": entry_type})
            continue
        authors = c.get("authors")
        if not authors or c.get("first_author") != authors[0]:
            problems["missing_authors"].append({"id": cid})
        elif any(TRUNCATED_AUTHOR_RE.search(a) for a in authors):
            problems["truncated_author_list"].append({"id": cid, "authors": authors})
        for field in REQUIRED_VENUE_FIELDS_BY_TYPE.get(entry_type, ()):
            if not c.get(field):
                problems["missing_venue_fields"].append({"id": cid, "missing_field": field})
        if "doi" in c and f"doi = {{{c['doi']}}}" not in refs_bib_text:
            problems["doi_mismatches"].append({"id": cid, "doi": c["doi"]})
        if entry_type == "misc" and (c.get("journal") or c.get("booktitle")):
            problems["misc_with_venue_info"].append({"id": cid})
        record = audit_by_id.get(cid)
        if record is None:
            problems["audit_missing"].append(cid)
        elif not record.get("pass"):
            problems["audit_failed"].append({"id": cid, "detail": record.get("mismatches")})
    grb = _load_module("generate_refs_bib", PAPER_TEX_DIR / "generate_refs_bib.py")
    refs_bib_matches = refs_bib_text == grb.generate()
    ok = refs_bib_matches and not any(problems.values())
    return {"pass": ok, "total_citations": len(citations), "refs_bib_matches_generator": refs_bib_matches,
            "audited": len(audit_by_id), **problems}


# ---------------------------------------------------------------------------
# Repository lints, reported as gate rows
# ---------------------------------------------------------------------------

def _lint(cmd: list[str]) -> dict:
    r = run([sys.executable, *cmd], cwd=str(REPO_ROOT))
    return {"pass": r.returncode == 0, "command": " ".join(["python", *cmd]),
            "output_tail": (r.stdout + r.stderr).strip().splitlines()[-5:]}


def lint_terminology() -> dict:
    return _lint(["-m", "lint.terminology"])


def lint_proof_status() -> dict:
    return _lint(["-m", "checkers.proof_status_lint"])


def lint_typed_numerals() -> dict:
    return _lint(["-m", "lint.typed_numerals"])


def lint_populated_freshness() -> dict:
    return _lint(["paper/populate.py", "--check"])


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

GATES = {
    "G1_build": gate_g1_build,
    "G2_token_purity": gate_g2_token_purity,
    "G3_number_parity": gate_g3_number_parity,
    "G4_prose_parity": gate_g4_prose_parity,
    "G5_structure_parity": gate_g5_structure_parity,
    "G6_disclosure_and_banners": gate_g6_disclosure_and_banners,
    "G7_sidecar_sync": gate_g7_sidecar_sync,
    "G8_citation_completeness": gate_g8_citation_completeness,
    "G9_bibliography_quality": gate_g9_bibliography_quality,
    "L_terminology": lint_terminology,
    "L_proof_status": lint_proof_status,
    "L_typed_numerals": lint_typed_numerals,
    "L_populated_freshness": lint_populated_freshness,
}


def gate_table(results: dict) -> str:
    rows = ["| gate | result |", "|---|---|"]
    rows += [f"| {name} | {'PASS' if g['pass'] else 'FAIL'} |" for name, g in results.items()]
    return "\n".join(rows)


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    names = [a for a in args if a in GATES] or list(GATES)
    results = {name: GATES[name]() for name in names}
    all_pass = all(g["pass"] for g in results.values())
    if names == list(GATES):
        report = {"all_pass": all_pass, "gates": results}
        REPORT_PATH.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    for name, g in results.items():
        if not g["pass"]:
            print(f"--- {name} detail ---")
            print(json.dumps(g, indent=2, sort_keys=True)[:6000])
    print(gate_table(results))
    print("ALL GATES PASS" if all_pass else "GATE FAILURE -- see detail above")
    return 0 if all_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
