#!/usr/bin/env python3
"""Generate paper-tex/main.tex from the populated manuscript (paper 6).

    python paper-tex/build_main_tex.py

main.tex is a build product, never hand-edited: pandoc renders
paper/paper6-draft-v0.1-populated.md through paper-tex/template.tex (paper 5's preamble, see
that file) with --natbib citations and the figures.lua filter. Each SVG figure under
paper/figs/ is converted to PDF beside main.tex with rsvg-convert under the same fixed
SOURCE_DATE_EPOCH the gates use, so two runs give identical bytes.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

PAPER_TEX_DIR = Path(__file__).resolve().parent
REPO_ROOT = PAPER_TEX_DIR.parent
SOURCE_MD = REPO_ROOT / "paper" / "paper6-draft-v0.1-populated.md"
FIGS_DIR = REPO_ROOT / "paper" / "figs"
TEMPLATE = PAPER_TEX_DIR / "template.tex"
FILTER = PAPER_TEX_DIR / "filters" / "figures.lua"
MAIN_TEX = PAPER_TEX_DIR / "main.tex"
# Same content-stable epoch as gates/run_gates.py and make_arxiv_tarball.py.
SOURCE_DATE_EPOCH = "1786609963"

HEADER = (
    "% Generated by paper-tex/build_main_tex.py from paper/paper6-draft-v0.1-populated.md\n"
    "% through paper-tex/template.tex. Do not edit; edit the manuscript and rebuild.\n"
)


def convert_figures() -> list[Path]:
    env = {**os.environ, "SOURCE_DATE_EPOCH": SOURCE_DATE_EPOCH, "TZ": "UTC"}
    out = []
    for svg in sorted(FIGS_DIR.glob("*.svg")):
        pdf = PAPER_TEX_DIR / f"{svg.stem}.pdf"
        subprocess.run(["rsvg-convert", "-f", "pdf", "-o", str(pdf), str(svg)], check=True, env=env)
        out.append(pdf)
    return out


def render() -> str:
    r = subprocess.run(
        ["pandoc", str(SOURCE_MD), "-f", "markdown", "-t", "latex", "--template", str(TEMPLATE),
         "--natbib", "--lua-filter", str(FILTER), "--wrap=none", "--no-highlight"],
        check=True, capture_output=True, text=True)
    return HEADER + r.stdout


def main() -> int:
    if not SOURCE_MD.exists():
        print(f"build_main_tex: {SOURCE_MD} missing; run python paper/populate.py first", file=sys.stderr)
        return 1
    figs = convert_figures()
    MAIN_TEX.write_text(render(), encoding="utf-8")
    print(f"build_main_tex: wrote {MAIN_TEX.relative_to(REPO_ROOT)} and {len(figs)} figure(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
