#!/usr/bin/env python3
"""Generate paper-tex/main.tex from the populated manuscript (paper 6).

    python paper-tex/build_main_tex.py

main.tex is a build product, never hand-edited: pandoc renders
paper/paper6-draft-v0.1-populated.md through paper-tex/template.tex (paper 5's preamble, see
that file) with --natbib citations and the figures.lua filter. Each figure's PDF, drawn by its
own script under paper/figs/ (matplotlib, bundled fonts, fixed metadata), is copied beside
main.tex; nothing is converted here (round-one finding F2).
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

PAPER_TEX_DIR = Path(__file__).resolve().parent
REPO_ROOT = PAPER_TEX_DIR.parent
SOURCE_MD = REPO_ROOT / "paper" / "paper6-draft-v0.1-populated.md"
FIGS_DIR = REPO_ROOT / "paper" / "figs"
TEMPLATE = PAPER_TEX_DIR / "template.tex"
FILTER = PAPER_TEX_DIR / "filters" / "figures.lua"
MAIN_TEX = PAPER_TEX_DIR / "main.tex"
HEADER = (
    "% Generated by paper-tex/build_main_tex.py from paper/paper6-draft-v0.1-populated.md\n"
    "% through paper-tex/template.tex. Do not edit; edit the manuscript and rebuild.\n"
)


def convert_figures() -> list[Path]:
    """Copy each committed figure PDF (paper/figs/*.pdf) beside main.tex."""
    out = []
    for pdf in sorted(FIGS_DIR.glob("*.pdf")):
        shutil.copyfile(pdf, PAPER_TEX_DIR / pdf.name)
        out.append(PAPER_TEX_DIR / pdf.name)
    return out


def render() -> str:
    r = subprocess.run(
        ["pandoc", str(SOURCE_MD), "-f", "markdown", "-t", "latex", "--template", str(TEMPLATE),
         "--natbib", "--lua-filter", str(FILTER), "--wrap=none", "--no-highlight"],
        check=True, capture_output=True, text=True)
    return HEADER + r.stdout


def main() -> int:
    if not SOURCE_MD.exists():
        print(f"build_main_tex: {SOURCE_MD} missing; run python paper/populate.py first", file=sys.stderr)
        return 1
    figs = convert_figures()
    MAIN_TEX.write_text(render(), encoding="utf-8")
    print(f"build_main_tex: wrote {MAIN_TEX.relative_to(REPO_ROOT)} and {len(figs)} figure(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
