#!/usr/bin/env python3
"""Generate the arXiv sidecars from the populated manuscript (paper 6, gate G7).

    python paper-tex/make_sidecars.py            # write arxiv-abstract.txt and arxiv-metadata.txt
    python paper-tex/make_sidecars.py --check    # exit 1 if either committed file is stale

In paper 5 the sidecars were hand-maintained and G7 checked them for drift. Here both are
generated from the manuscript's own front matter, so they cannot drift; G7 regenerates them
and requires byte equality with the committed files.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

PAPER_TEX_DIR = Path(__file__).resolve().parent
REPO_ROOT = PAPER_TEX_DIR.parent
SOURCE_MD = REPO_ROOT / "paper" / "paper6-draft-v0.1-populated.md"
ABSTRACT_PATH = PAPER_TEX_DIR / "arxiv-abstract.txt"
METADATA_PATH = PAPER_TEX_DIR / "arxiv-metadata.txt"
REPOSITORY_URL = "https://github.com/besanson/gigo-jev-probe"


def front_matter(path: Path = SOURCE_MD) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: no YAML front matter")
    return yaml.safe_load(text[4:text.index("\n---\n", 4)])


def plain(markdown: str) -> str:
    r = subprocess.run(["pandoc", "-f", "markdown", "-t", "plain", "--wrap=none"],
                       input=markdown, capture_output=True, text=True, check=True)
    return r.stdout.strip()


def abstract_text(fm: dict) -> str:
    return plain(fm["abstract"]) + "\n"


def metadata_text(fm: dict) -> str:
    return "\n".join([
        "arXiv submission metadata (generated by paper-tex/make_sidecars.py; do not edit)",
        "",
        "Title",
        "-----",
        plain(fm["title"]),
        "",
        "Author line",
        "-----------",
        f"{fm['author']} ({fm['thanks']})",
        "",
        "Categories",
        "----------",
        "Primary: cs.AI. Cross-lists: cs.LO, cs.CR.",
        "",
        "License",
        "-------",
        "CC BY 4.0",
        "",
        "Linked artifact",
        "---------------",
        f"GitHub repository: {REPOSITORY_URL}",
        "",
    ])


def expected() -> dict[Path, str]:
    fm = front_matter()
    return {ABSTRACT_PATH: abstract_text(fm), METADATA_PATH: metadata_text(fm)}


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    files = expected()
    if "--check" in args:
        stale = [p.name for p, t in files.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        print("make_sidecars: " + (f"stale {stale}" if stale else "ok"))
        return 1 if stale else 0
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
    print(f"make_sidecars: wrote {', '.join(p.name for p in files)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
